// How each template presents particular sections, so people know what they are filling in.
export const templateSectionNotes = {
  azurill: { experience: 'Each role is marked on a timeline down the main column.', skills: 'Skills sit in the left sidebar; keep each group short.' },
  bronzor: { summary: 'Every section heading sits in a narrow column to the left of its content.' },
  chikorita: { skills: 'Shown in white on the coloured right sidebar.', summary: 'Sits under your name in the main column.' },
  ditgar: { summary: 'Shown as a highlighted panel at the top of the main column, without a heading.', experience: 'Job titles are marked with an accent bar.' },
  ditto: { summary: 'Your name and headline sit in the coloured band; the summary starts the main column.' },
  gengar: { summary: 'Shown as a highlighted panel at the top of the main column, without a heading.' },
  glalie: { skills: 'Listed in the tinted left sidebar under your boxed contact details.' },
  kakuna: { summary: 'Everything is centred, so shorter lines read best.' },
  lapras: { summary: 'Each section is drawn as its own outlined card.' },
  leafish: { skills: 'Listed in the right sidebar beside your experience.' },
  meowth: { experience: 'Position, organisation and dates share one line, so keep titles short.', education: 'Degree, school and dates share one line.' },
  pikachu: { summary: 'Your name and contact details sit in the solid header block above it.' },
  rhyhorn: { summary: 'A minimal header with lots of whitespace; short paragraphs suit it best.' },
  scizor: { summary: 'Section headings are printed in capitals with a rule above each one.' },
  'navy-professional': { education: 'This template puts education first.' },
  'curve-academic': { experience: 'Clearly dated entries; add start and end dates for every role.' },
  'minimal-academic': { personal: 'Your contact details print as the first section, with a label beside each one.', summary: 'Printed as "About me" in grey body text.' },
  'libre-cv': { skills: 'Shown in the right column, each group as a row with its name in small capitals.', experience: 'The organisation is in bold on the first line, your role and dates on the second.' },
  'simple-hipster': { summary: 'Sits in the grey sidebar under your photo, right-aligned.', experience: 'Dates sit in the margin beside a timeline rule.', skills: 'Each skill is printed as its own grey label.' },
  'keywords-cv': { summary: 'Runs full width; everything else is in two columns below it.', experience: 'The heading reads "Role / dates", so keep titles short.' },
  'elegant-resume': { experience: 'The organisation and role sit on one line in capitals, then location and dates.' },
  'developer-cv': { summary: 'Sits beside your skills at the top of the page; two or three sentences fit best.', projects: 'The tools you list print in the left margin of each project.' }
}
