// Families to self-host. The fetch script keeps only those it can download with an OFL or Apache licence
// and writes src/fonts/fontCatalogue.json from what actually succeeded.
// tags: professional, modern, friendly, academic, technical, elegant, editorial, compact, geometric, humanist, classic, bold, creative
// roles: body (safe for body text) and/or heading. atsSafe: plain, highly legible letterforms.
const sans = (name, tags, extra = {}) => ({ name, category: 'Sans serif', generic: 'sans-serif', tags, roles: ['body', 'heading'], atsSafe: true, ...extra })
const serif = (name, tags, extra = {}) => ({ name, category: 'Serif', generic: 'serif', tags, roles: ['body', 'heading'], atsSafe: true, ...extra })
const slab = (name, tags, extra = {}) => ({ name, category: 'Slab serif', generic: 'serif', tags, roles: ['body', 'heading'], atsSafe: true, ...extra })
const mono = (name, tags, extra = {}) => ({ name, category: 'Monospace', generic: 'monospace', tags, roles: ['body', 'heading'], atsSafe: false, ...extra })
const display = (name, tags, generic = 'sans-serif', extra = {}) => ({ name, category: 'Display', generic, tags, roles: ['heading'], atsSafe: false, ...extra })

export const fontSources = [
  // Sans serif
  sans('Inter', ['professional', 'modern', 'neutral', 'technical']),
  sans('Roboto', ['professional', 'modern', 'neutral']),
  sans('Open Sans', ['professional', 'friendly', 'humanist']),
  sans('Lato', ['professional', 'friendly', 'humanist']),
  sans('Source Sans 3', ['professional', 'humanist', 'neutral'], { legacyName: 'Source Sans Pro' }),
  sans('Work Sans', ['modern', 'friendly']),
  sans('Karla', ['modern', 'friendly', 'compact']),
  sans('Fira Sans', ['technical', 'humanist', 'modern']),
  sans('Nunito Sans', ['friendly', 'modern']),
  sans('IBM Plex Sans', ['professional', 'technical', 'corporate']),
  sans('Libre Franklin', ['professional', 'classic', 'editorial']),
  sans('Montserrat', ['modern', 'geometric', 'bold']),
  sans('DM Sans', ['modern', 'geometric', 'friendly']),
  sans('Alegreya Sans', ['humanist', 'editorial', 'friendly']),
  sans('Noto Sans', ['professional', 'neutral']),
  sans('Raleway', ['elegant', 'modern']),
  sans('Poppins', ['modern', 'geometric', 'friendly']),
  sans('Manrope', ['modern', 'technical', 'geometric']),
  sans('Plus Jakarta Sans', ['modern', 'friendly', 'professional']),
  sans('Outfit', ['modern', 'geometric']),
  sans('Figtree', ['modern', 'friendly', 'professional']),
  sans('Urbanist', ['modern', 'geometric']),
  sans('Lexend', ['friendly', 'modern', 'readable']),
  sans('Mulish', ['modern', 'friendly', 'compact']),
  sans('Rubik', ['friendly', 'modern']),
  sans('Barlow', ['technical', 'compact', 'modern']),
  sans('Hind', ['professional', 'compact']),
  sans('PT Sans', ['professional', 'humanist', 'classic']),
  sans('Cabin', ['humanist', 'friendly']),
  sans('Archivo', ['professional', 'compact', 'technical']),
  sans('Public Sans', ['professional', 'neutral', 'corporate']),
  sans('Red Hat Display', ['modern', 'bold']),
  sans('Red Hat Text', ['modern', 'professional']),
  sans('Sora', ['modern', 'technical', 'geometric']),
  sans('Space Grotesk', ['modern', 'technical', 'creative']),
  sans('Josefin Sans', ['elegant', 'geometric', 'creative']),
  sans('Quicksand', ['friendly', 'creative'], { atsSafe: false }),
  sans('Overpass', ['technical', 'modern']),
  sans('Heebo', ['professional', 'modern', 'neutral']),
  sans('Assistant', ['professional', 'compact']),
  sans('Titillium Web', ['technical', 'modern']),
  sans('Exo 2', ['technical', 'creative'], { atsSafe: false }),
  sans('Jost', ['modern', 'geometric', 'elegant']),
  sans('Albert Sans', ['modern', 'professional']),
  sans('Be Vietnam Pro', ['modern', 'friendly', 'professional']),
  sans('Onest', ['modern', 'neutral']),
  sans('Instrument Sans', ['modern', 'professional', 'compact']),
  sans('Schibsted Grotesk', ['editorial', 'modern']),
  sans('Hanken Grotesk', ['modern', 'neutral']),
  sans('Commissioner', ['modern', 'professional']),
  sans('Epilogue', ['modern', 'editorial', 'bold']),
  sans('Encode Sans', ['technical', 'compact']),
  sans('Asap', ['friendly', 'compact']),
  sans('Signika', ['friendly', 'humanist']),
  sans('Mukta', ['professional', 'compact']),
  sans('Atkinson Hyperlegible', ['readable', 'professional', 'accessible']),
  sans('Golos Text', ['modern', 'neutral']),
  sans('Arimo', ['professional', 'neutral', 'classic'], { note: 'Metric-compatible with Arial' }),
  sans('Carlito', ['professional', 'corporate'], { note: 'Metric-compatible with Calibri' }),
  sans('Oxygen', ['friendly', 'technical']),
  sans('Kanit', ['modern', 'bold']),
  sans('Barlow Semi Condensed', ['compact', 'technical']),
  sans('IBM Plex Sans Condensed', ['compact', 'technical', 'corporate']),
  sans('Roboto Condensed', ['compact', 'professional']),
  sans('Ubuntu Sans', ['friendly', 'technical']),
  // Serif
  serif('Merriweather', ['professional', 'classic', 'readable']),
  serif('PT Serif', ['professional', 'classic']),
  serif('Lora', ['elegant', 'editorial', 'friendly']),
  serif('Crimson Text', ['academic', 'classic', 'elegant']),
  serif('EB Garamond', ['academic', 'classic', 'elegant']),
  serif('Cormorant Garamond', ['elegant', 'editorial'], { atsSafe: false }),
  serif('Domine', ['professional', 'bold', 'classic']),
  serif('Libre Baskerville', ['classic', 'academic', 'professional'], { legacyName: 'Baskerville' }),
  serif('IBM Plex Serif', ['professional', 'technical', 'corporate']),
  serif('Source Serif 4', ['professional', 'editorial', 'academic']),
  serif('Noto Serif', ['professional', 'classic']),
  serif('Spectral', ['elegant', 'editorial']),
  serif('Libre Caslon Text', ['classic', 'editorial', 'academic']),
  serif('Cardo', ['academic', 'classic']),
  serif('Gelasio', ['professional', 'classic'], { note: 'Metric-compatible with Georgia' }),
  serif('Literata', ['readable', 'editorial', 'academic']),
  serif('Newsreader', ['editorial', 'elegant']),
  serif('Fraunces', ['creative', 'editorial', 'bold'], { atsSafe: false }),
  serif('Alegreya', ['editorial', 'academic']),
  serif('Vollkorn', ['classic', 'academic']),
  serif('Crimson Pro', ['academic', 'elegant', 'classic']),
  serif('Frank Ruhl Libre', ['classic', 'editorial']),
  serif('Petrona', ['editorial', 'modern']),
  serif('Brygada 1918', ['classic', 'elegant']),
  serif('Besley', ['classic', 'bold']),
  serif('DM Serif Text', ['elegant', 'editorial']),
  serif('Tinos', ['professional', 'classic'], { note: 'Metric-compatible with Times New Roman' }),
  serif('Caladea', ['professional', 'corporate'], { note: 'Metric-compatible with Cambria' }),
  serif('Old Standard TT', ['academic', 'classic'], { atsSafe: false }),
  serif('Playfair', ['elegant', 'editorial'], { atsSafe: false }),
  serif('Instrument Serif', ['elegant', 'editorial'], { atsSafe: false, roles: ['heading'] }),
  serif('Roboto Serif', ['professional', 'modern']),
  serif('Noticia Text', ['editorial', 'professional']),
  serif('Rasa', ['editorial', 'friendly']),
  // Slab serif
  slab('Roboto Slab', ['professional', 'bold', 'modern']),
  slab('Arvo', ['bold', 'classic']),
  slab('Zilla Slab', ['editorial', 'friendly']),
  slab('Bitter', ['readable', 'professional']),
  slab('Josefin Slab', ['elegant', 'creative'], { atsSafe: false }),
  slab('Aleo', ['friendly', 'professional']),
  slab('Rokkitt', ['bold', 'compact']),
  slab('Crete Round', ['friendly', 'bold']),
  // Monospace
  mono('Roboto Mono', ['technical']),
  mono('IBM Plex Mono', ['technical', 'corporate']),
  mono('JetBrains Mono', ['technical', 'modern']),
  mono('Fira Code', ['technical']),
  mono('Source Code Pro', ['technical', 'professional']),
  mono('Space Mono', ['technical', 'creative']),
  mono('Inconsolata', ['technical', 'compact']),
  mono('DM Mono', ['technical', 'modern']),
  mono('Courier Prime', ['classic', 'technical']),
  mono('Cousine', ['technical'], { note: 'Metric-compatible with Courier New' }),
  // Display — headings only
  display('Playfair Display', ['elegant', 'editorial', 'bold'], 'serif'),
  display('Bebas Neue', ['bold', 'modern', 'creative']),
  display('Oswald', ['bold', 'compact', 'modern']),
  display('Archivo Black', ['bold', 'modern']),
  display('Abril Fatface', ['bold', 'editorial'], 'serif'),
  display('DM Serif Display', ['elegant', 'editorial'], 'serif'),
  display('Prata', ['elegant', 'classic'], 'serif'),
  display('Cinzel', ['elegant', 'classic'], 'serif'),
  display('Anton', ['bold', 'compact']),
  display('Syne', ['creative', 'modern']),
  display('Unbounded', ['creative', 'bold']),
  display('Big Shoulders Display', ['bold', 'compact', 'creative']),
  display('Bodoni Moda', ['elegant', 'editorial'], 'serif'),
  display('Marcellus', ['elegant', 'classic'], 'serif'),
  display('League Spartan', ['bold', 'geometric', 'modern'])
]
